name: modular_web
description: Everything you need to build modular apps in dart/flutter.
version: 0.1.0
publish_to: none
repository: https://github.com/makoConstruct/modular_web

environment:
  sdk: ^3.6.0

dependencies:
  # path: ^1.8.0
  cbor: ^6.3.3
  crypto: ^3.0.6
  dataclass: ^1.0.0
  build_runner: ^2.0.0
  build: ^2.0.0
  woodslist: ^0.1.0
  set_list: ^0.2.0

dependency_overrides:
  set_list:
    path: ../SetList/
    version: ^0.2.0
  woodslist:
    path: ../termpose/dart/
    version: 0.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
