[package]
name = "modular_types"
description = "not published, just kept here to illustrate the most efficient way to represent and implement upcastable modular objects, in case we ever need that."
version = "0.1.0"
edition = "2024"

[dependencies]
